name: Shell Commsnds

on: [push, pull_request]
jobs:
    run-shell-command:
      runs-on: ubuntu-20.04
      steps:
        - name: echo a string
          run: echo "Hello World"
        - name: multiline script
          run: |
              echo "nodepm version is $(node -v)
              echo "node version is $(npm -v)